
services:
  db:
    image: postgres:16
    container_name: blaurose_container2
    environment:
      POSTGRES_DATABASE: blaurose_database
      POSTGRES_USER: blaurose
      POSTGRES_PASSWORD: blaurose
      TZ: 'Asia/Tokyo'
      PGDATA: /var/lib/postgresql/data/pgdata
    volumes:
      - ./db/postgres:/var/lib/postgresql/data
      - ./db/logs:/var/log
    ports:
      - 5432:5432

